### ISSUE TITLE
Could not find cordova.js script tag. Plugin loading may fail.

### ISSUE THREAD

**Issue by jamorton** [phonegap/phonegap-cli#134]
`Could not find cordova.js script tag. Plugin loading may fail.`

I get this javascript error from phonegap.js. I think it's because phonegap.js is just a renamed cordova.js, so it's not looking for the right script tag.

**Comment by brianlmerritt** [comment]
I haven't read the whole thread 1000%, but I do hope everyone has discovered that cordova.js and/or phonegap.js are added when the app is created.

Therefore, if you test on a browser, the .js files will therefore be missing because they are dependent upon the mobile platform, hence why they are set when you create the app for ios, android etc etc.

**Comment by Sylvian** [comment]
Hi,
i've got the same error:

> phonegap.js:1917 Could not find cordova.js script tag. Plugin loading may fail.
> file:///android_asset/www/phonegap.js:1917

JS File giving the notice:
```
var pathPrefix = findCordovaPath();
    if (pathPrefix === null) {
        console.log('Could not find cordova.js script tag. Plugin loading may fail.');
        pathPrefix = '';
    }
```

Hope this could help you debugging.
