### ISSUE TITLE
config.xml icons completely ignored when adding platform ios

### ISSUE THREAD

**Issue by pixoto** [phonegap/phonegap-cli#265]
```
$ phonegap create ios
$ cd app
```

config.xml

```
    <icon src="res/icon/ios/icon-57.png"            gap:platform="ios"        width="57" height="57" />
    <icon src="res/icon/ios/icon-72.png"            gap:platform="ios"        width="72" height="72" />
    <icon src="res/icon/ios/icon-57-2x.png"         gap:platform="ios"        width="114" height="114" />
    <icon src="res/icon/ios/icon-72-2x.png"         gap:platform="ios"        width="144" height="144" />
```

Edit the icons in the www/res/icon folder

```
$ phonegap run ios
```

adds the ios platform and creates an ios app that still uses the cordova icons

**Comment by sophyandres** [comment]
infinito84's answer worked for me

**Comment by elixias** [comment]
My Cordova version is 4.2,testing in Android.

During build, phonegap copies the icons from the www/res/icons/ios folder into the ant-build's android res folder, so the custom icons are never used and always replaced by the default.

ended up replacing the icons in ios so that the android builds the icons correctly...

**Comment by shreyasnavada91** [comment]
As elixias mentioned , there is a bug while building the platform.
Android build searches for ios icons, and ios build searches for both ios and windows icons.

**Comment by webbprofessor** [comment]
This is extremely frustrating...after countless attempts the only thing that worked for me via Phonegap Build (3.7.0) was this update to config.xml 

<h1>add</h1>
< icon src='res/icon.png'   />

<h1>delete</h1>
     <platform name="android">
              <icon src="res/android/ldpi.png" density="ldpi" />
              <icon src="res/android/mdpi.png" density="mdpi" />
              <icon src="res/android/hdpi.png" density="hdpi" />
              <icon src="res/android/xhdpi.png" density="xhdpi" />  
     </platform>

**Comment by sachux** [comment]
Thanks elixias. Finally got it.

**Comment by dsc-mike** [comment]
+1 to elixias' answer

**Comment by borjasanes** [comment]
I was reading a lot of this problem and finally I solved it. I had to open the phonegap project with android Studio. Once opened, I copied the icons to platforms/android/res/ in his properly folder and calling it icon.png

pd. other time I had to create a new phonegap project and copy all the files and then do what i say before

good luck this problem gived me headache

**Comment by domenicomazza** [comment]
I inadvertently fixed this bug for an iOS build by using the PhoneGap CLI version of the hello world app and moving the config.xml file to the `www` directory (and adjusting file links by omitting `www/`), see http://stackoverflow.com/questions/33550787/phonegap-build-disallowoverscroll-not-working-on-ios. This also solved issues around honouring `DisallowOverscroll` which I originally searched for. It seems like PhoneGap build is outright ignoring the config.xml file unless it's moved into `www`.

**Comment by farhanwazir** [comment]
It's not about cleaning or caching issues at all. The problem is PhoneGap includes all possible launch images in project template by default. These files are under Resources folder and copied to bundle's root folder on build event. Although I properly selected my own launch images in Xcode (Target/Summary screen), default PhoneGap's specific files e.g. Default~iphone.png overridden my files :(

Once issue is identified, you can fix it someway, but I prefer below steps:

1. Delete all default icons and splashscreen files under /platforms/ios/AppName/icons and /splash folders. You surely don't need these placeholder images.

2. In Xcode, select Targets/AppName, then tab Build Phases, delete all file names of images in the above step in section Copy Bundle Resources.

3. Add your own images files for app icon and launch images here.

4. Edit Info.plist file (file AppName-Info.plist under /platforms/ios/AppName/) to include your images, you will need to use CFBundleIcons and UILaunchImageFile keys. Go to iOS developer site for reference.

[Best solution by Tien Do](http://stackoverflow.com/questions/18866450/why-phonegap-always-shows-default-splashscreen-image)
