### ISSUE TITLE
Plugin Not Loading With `phonegap serve`

### ISSUE THREAD

**Issue by jeresig** [phonegap/phonegap-cli#315]
Issue: Attempting to load a simple `js-module` plugin inside the `phonegap serve` environment seems to fail.

My version of the Phonegap cli: 3.4.0-0.19.21

I've bundled a trivial failing case into a zip file, which you can find here:
http://ejohn.org/files/phonegap-serve-bug.zip

Additionally I've outlined the detailed steps on how to reproduce this, below:
## Steps to reproduce:

Run the following commands:

```
phonegap create hello com.example.hello HelloWorld
cd hello
phonegap local plugin add https://github.com/oauth-io/oauth-phonegap
```

Add the following line to www/config.xml:

```
<gap:plugin name="com.phonegap.plugins.oauthio" version="0.1.1" />
```

Add the following line inside of the `receivedEvent` callback inside `www/js/index.js`:

```
alert(typeof OAuth)
```

Run the following commands:

```
cd ..
phonegap run ios
```

You should see an alert that reads "object" (this is the expected result).

Now do the following:

```
phonegap serve
```

Connect with a client (in my case, on a physical iPad). You should see an alert that says "undefined". This is not the expected result - and in fact the module never seems to load even if you wait for a long time (adding a 5 second timeout yields the same result).

**Comment by Zarkonnen** [comment]
This is still not working in June 2016, nor is it mentioned anywhere in the documentation for getting set up. I just used an entire work-day tearing out my hair because I followed all the steps but the plugin didn't load. Can you please add a note [here](http://docs.phonegap.com/getting-started/2-install-mobile-app/) mentioning the lack of plugin support?

**Comment by christocracy** [comment]
I seriously doubt your issue has anything to do with the original issue
reported 2 years ago on 3.x.

Do you have some logs?

On Friday, June 10, 2016, David Stark <notifications@github.com> wrote:

> This is still not working in June 2016, nor is it mentioned anywhere in
> the documentation for I getting set up. I just used an entire work-day
> tearing out my hair because I followed all the steps but the plugin didn't
> load. Can you please add a note here
> <http://docs.phonegap.com/getting-started/2-install-mobile-app/>
> mentioning the lack of plugin support?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/phonegap/phonegap-cli/issues/315#issuecomment-225156073>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAA6lxxbvbXJuyag-nhAtZ6u5g7cXmfVks5qKUaugaJpZM4B7Fwe>
> .
>


-- 
Snet form Gmail Mobile

**Comment by Zarkonnen** [comment]
@christocracy Of course! Here's the reproduction steps:

**Reproduce**
```
phonegap create test
cd test
phonegap plugin add de.appplant.cordova.plugin.local-notification
cd www
```

Edit index.html to include the following line just before app.initialize(): document.addEventListener('deviceready', function () { alert("cordova.plugins " + cordova.plugins); });

`phonegap serve
`
Open the app via the PhoneGap app on an iPad.

**Expected**

alert saying "cordova.plugins [object Object]"

**Observed**

alert saying "cordova.plugins undefined"

Running the app in the android emulator using "phonegap run android" gives the correct alert message.

**Comment by dbessa1** [comment]
I also have the same problem. What you did not realize is that this problem does not only occur if the plugin is from a third party. If you test with the device variable that belongs to a native plugin, you will also see that the plugin was not loaded because the variable will be "undefined". I have two android phones, in one of them the app loads all the plugins correctly on 80% of the times I open the app. Already on my other mobile phone the app rarely loads the plug-ins.
