### ISSUE TITLE
Chrome Remote Debugging support

### ISSUE THREAD

**Issue by Globegitter** [phonegap/phonegap-cli#520]
Having the app (http://app.phonegap.com/) is pretty sweet but it does seem to lack the [Chrome Remote debugging feature](https://developer.chrome.com/devtools/docs/remote-debugging) which is useful in all cases and necessary in some.

So in the necessary cases you have to deploy your app all over again - already improved workflow bout would really love to see some easy debugging support :)

Edit: Ahh, I am seeing console.logs are already being reported. Well that makes it all at least much easier and not quite as necessary anymore.

Thanks for this great tool!

**Comment by mwbrooks** [comment]
I'm going to close this issue because it's not entirely within the CLI scope.

PhoneGap Developer App has a backlog task to investigate production web inspector usage: https://github.com/phonegap/phonegap-app-developer/issues/49

PhoneGap CLI also has a list of modules that could be integrated to help with debugging: https://github.com/phonegap/phonegap-cli/issues/539
