### ISSUE TITLE
Should we autosave platforms and plugins?

### ISSUE THREAD

**Issue by stevengill** [phonegap/phonegap-cli#528]
Since pg-cliI runs `cordova platform add PLATFORM` when a user runs `phonegap run PLATFORM` or `phonegap build PLATFORM`. Users don't have a chance to save their platform into their config.xml. They would have to run `cordova/phonegap platform add PLATFORM --save` manually before running phonegap run/build. 

Few options off the top of my head:

1) catch `--save` flag and pass it to `cordova platform add PLATFORM`. This would mean users would have to explicitly save a platform. `phonegap build PLATFORM --save` `phonegap run PLATFORM --save`

2) make pg-cli autosave. So we replace logic to use `cordova platform add PLATFORM --save` and `cordova platform rm PLATFORM --save` under the hood. 

3) Run `cordova platform save` before every build/run which will add any installed platforms to config.xml. Just another way to autosave. `cordova plugin save` does the same for plugins. 

Reasons why we don't autosave in cordova-cli is because we wanted to be more like npm. npm requires users to explicitly save dependencies in their package.json files with `--save` or manually adding them.

Since pg-cli workflow doesn't give users the chance to add platforms, autosaving might be the way to go for platforms. Users should still use the --save command for plugins. 

Thoughts?

**Comment by mwbrooks** [comment]
Thanks for brining up this discussion @stevengill.

I like that the Cordova CLI takes the explicit command stance. As a core framework used by other projects, it's more predictable and reliable when it requires explicit actions. The PhoneGap CLI, on the hand, can ease repetitive tasks while still exposing the full functionality when desired.

I prefer option 2). When a user executes `phonegap run <platform>` or `phonegap build <platform>` we check if the platform exists. If it does, then we continue to run or build the project. If the platform does not exist, then we execute `cordova platform add <platform> --save` (previously, we executed `cordova platform add <platform>`). I prefer this method because it matches the functionality that previously exists and does not impact existing projects.

I expect that we can update [this line of code](https://github.com/phonegap/phonegap-cli/blob/master/lib/phonegap/cordova.js#L177-L178) with the `--save` flag to get the proper functionality.

**Comment by stevengill** [comment]
Sounds good. I will look into implementing option 2
