### ISSUE TITLE
Cannot find icon.png when add android platform

### ISSUE THREAD

**Issue by realtebo** [phonegap/phonegap-cli#546]
from a folder I did

    phonegap create HelloWorld
    cd HelloWorld
    phonegap platform add android

And I got 

```
npm
 http GET https://registry.npmjs.org/cordova-android

npm
http 304 https://registry.npmjs.org/cordova-android

Adding android project...

Creating Cordova project for the Android platform:

        Path: platforms\android

        Package: com.phonegap.helloworld
        Name: Hello World
        Activity: MainActivity
        Android target: android-22
Copying template files...

Android project created with cordova-android@4.0.2

cp: no such file or directory: C:\Users\mirko\Phonegap\HelloWorld\icon.png
```

My path (relevant portions)

    C:\>echo %PATH%
     ....
    C:\Program Files (x86)\Android\android-sdk\tools;
    C:\Program Files (x86)\Android\android-sdk\platform_tools;
    C:\apache-ant-1.9.6;\bin;
    
Also 

    C:\>phonegap -v
    5.1.1

What could be gone wrong?

**Comment by mwbrooks** [comment]
Hi @realtebo, this isn't anything to be concerned about. In the default `config.xml` you'll see a line that references:
```
<icon src="icon.png" />
```
Since this icon does not exist in your project (`HelloWorld/icon.png`), Android prints out the error. You can either delete the line in the `config.xml` (adding the platform-specific ones for Android) or update the default icon path.
