### ISSUE TITLE
Phonegap serve doesn't work

### ISSUE THREAD

**Issue by grostein** [phonegap/phonegap-cli#558]
On Arch linux when I launch "phonegap serve" it crashes without any output.

![senzanome](https://cloud.githubusercontent.com/assets/2891509/10934020/40c8d9d0-82dd-11e5-899e-4659c98da209.png)

**Comment by katart** [comment]
I'm having the same problem. I'm using Terminal on El Capitan.

PhoneGap v5.3.6
npm v3.3.6
node v5.0.0
git v2.4.9

**Comment by grostein** [comment]
Phonegap v5.3.6
Npm v3.3.10
Node v5.0.0

**Comment by mwbrooks** [comment]
Hey @grostein,

Thanks a ton for reporting this. At first I assumed it was due to Linux, but looks like both @katart and you are using Node v5.0. I'm currently using Node v4.0, so I'll update it and let you know what I find.

@katart, appreciate you chiming in with your environment settings. You may have saved me going down the Linux rabbit hole!

**Comment by grostein** [comment]
FYI I have update npm (3.3.12), still the same situation

**Comment by mwbrooks** [comment]
Alright, a brief update:

- I can re-create the issue using Node v5.0 as well.
- The issue is caused by `cordova-lib`, which it [recently fixed](https://issues.apache.org/jira/browse/CB-9935)
- `cordova-lib` has not published the fixed version on npm, so we cannot use it yet

I'll try to find a workaround for everyone until Cordova releases the fix.

**Comment by mwbrooks** [comment]
Alright everyone, thanks to @stevengill's efforts, Cordova has published the fix and I've updated the PhoneGap CLI.

Please update to `phonegap@5.3.7` to run on Node v5.0.0!

Thanks again for reporting this issue and helping us ship the fix!
