### ISSUE TITLE
Phonegap library silently fails after calling 'create' with invalid path

### ISSUE THREAD

**Issue by thewebdreamer** [phonegap/phonegap-cli#575]
I've noticed that the phonegab lib (5.4.0) silently fails when passing a path with 1 or more non existing folder. 

It would be nice to have a sanity check on the path before attempting to create a project and return an error in the callback when the path is wrong.

Little repro below (Node.js):
(Let's say the path is './folderA/folderB')

``` javascript
var phonegap = require('phonegap');

var options = myOptions; // pretend this is filled somewhere
                         // options.path = 'folderA/folderB'
                         // but folderA doesn't exist

phonegap.create({
  id: options.id || undefined,
  path: options.path || undefined,
  name: options.name || undefined,
  config: options.config || undefined,
  callback: function(error) {
    if(error) console.error(error.message); // no error message caught...
  },
});
```

**Comment by mwbrooks** [comment]
Hi @thewebdreamer,

It looks as though you have a minor reference error. The `phonegap.create` takes the callback as the second argument. So the function signature will look like: 

```javascript
phonegap.create(options, callback);
```

Here is an example of how it would look put together:

```javascript
var phonegap = require('phonegap');

var options = {
  path: '/path/to/my-app'
};

phonegap.create(options, function(e) {
  if (e) {
    console.log('Unexpected error:', e.message);
  }
  else {
    console.log('Successfully created project');
  }
});
```

Also, I noticed that `phonegap.create` does **not** automatically create missing subdirectories. This is because the underlining `cordova.create` does not support creating subdirectories. Is this a feature you're hoping for it to have?

**Comment by thewebdreamer** [comment]
Hey @mwbrooks,

I misread the function declaration. I guess it was getting a bit late!

Concerning the creation of the missing sub-directories, they would be a nice to have. It is not a blocker for me as I can handle it outside of phonegap.

Cheers

**Comment by filmaj** [comment]
Looks like this issue was resolved. Closing.
