### ISSUE TITLE
Enable debugging ON for phonegap cli 6.3.0 take too much time for loading app

### ISSUE THREAD

**Issue by mobileias** [phonegap/phonegap-cli#658]
If Turn ON debug mode from https://build.phonegap.com for

`<preference name="phonegap-version" value="cli-6.3.0"/>`
then phonegap added some script at the end of index.html

Now some time their server too slow or some time that gives error so our app also stuck some time and also take too much time to open

just for example

https://debug1.phonegap.com/target/target-script-min.js#ad0c51fe-ae06-11e5-82dc-22000bcc22 4c

this url take too much time
some time
https://debug2.phonegap.com/target/target-script-min.js#ad0c51fe-ae06-11e5-82dc-22000bcc22 4c
or https://debug3.phonegap.com/target/target-script-min.js#ad0c51fe-ae06-11e5-82dc-22000bcc22 4c

some time debug server give 404 error , too much channel live error .
So please help me for this type issue.

**Comment by surajpindoria** [comment]
Hi @mobileias,

I talked with the Build team and when you enable debugging from the website it adds `Weinre` to handle this. That may be what is causing the slow down you are describing. You have already posted this on the PhoneGap build forums so they will be able to assist you there.

I am going to close this issue here.
