### ISSUE TITLE
phonegap build error

### ISSUE THREAD

**Issue by sqAAps** [phonegap/phonegap-cli#671]
### Steps to Reproduce 
Please see image
![3](https://cloud.githubusercontent.com/assets/23194690/21134512/ed88aae6-c126-11e6-9857-68db2d64fbe9.png)

**Comment by surajpindoria** [comment]
What plugins are you using within your app? A quick google search on this error seems like it could be due to multiple dependencies that reference something that is has been included already.

http://stackoverflow.com/questions/32798816/unexpected-top-level-exception-com-android-dex-dexexception-multiple-dex-files

**Comment by filmaj** [comment]
With no response from the reporter, I am closing this issue down. If this is still a problem and you would like help in resolving it, please re-open the issue and we will do our best to help.
