### ISSUE TITLE
Can't add plugins

### ISSUE THREAD

**Issue by ismd** [phonegap/phonegap-cli#684]
### PhoneGap CLI, node & npm versions
PhoneGap 6.4.4
node 7.7.1
npm 4.3.0
### Expected Behaviour
cordova.plugins object contains added plugins on iOS and Android platform
### Actual Behaviour
cordova.plugins object contains installed plugins only in browser
### Steps to Reproduce 
System: up-to-dated Arch Linux (also tried on OS X)
```
pacman -S phonegap
mkdir test && cd test
phonegap create .
phonegap platform add ios android browser
# I want to use cordova-open plugin for example
phonegap plugin add cordova-open
# Adding alert(JSON.stringify(cordova.plugins)); to index.js in deviceready event handler.
phonegap serve
```
[cordova-open](https://www.npmjs.com/package/cordova-open) plugin should adds **cordova.plugins.disusered** property but it doesn't. The same trouble with other plugins.
Opening PhoneGap Developer App on iPhone or Android alerts object that contains only one plugin "barcodeScanner". I don't know why it's here, I didn't add it.
Opening app in browser alerts object that contains `disusered' property. It's right except this object is empty.
#### Sample Code that illustrates the problem
alert(JSON.stringify(cordova.plugins));
#### Error messages
No messages

**Comment by surajpindoria** [comment]
Hi @ismd,

The reason you are seeing this is because the developer app does not include the `cordova-open` plugin. We only include the core cordova plugins and a few others. If you were to compile and install the app to a device it should work as expected.

If you would like to continue using the developer app, you will need to create a custom build that includes this plugin. [Here](https://github.com/phonegap/phonegap-app-developer#adding-custom-plugins) are the instructions for creating a custom build.
