### ISSUE TITLE
Command 'phonegap run android' doesn't work

### ISSUE THREAD

**Issue by OlegDemkiv** [phonegap/phonegap-cli#685]
### PhoneGap CLI, node & npm versions
PhoneGap CLI 6.4.5
node 4.5.0
npm 4.3.0
Android SDK Tools 25.3.1

### Steps to Reproduce 
`phonegap run android`

#### Error messages
[phonegap] executing 'cordova platform add --save android' ...
[phonegap] completed 'cordova platform add --save android'
[phonegap] executing 'cordova run android ' ...
ANDROID_HOME=C:\Users\Lenovo\AppData\Local\Android\sdk

JAVA_HOME=C:\Program Files\java\jdk1.8.0_60

Error: Could not find gradle wrapper within Android SDK. Might need to update your Android SDK.
Looked here: C:\Users\Lenovo\AppData\Local\Android\sdk\tools\templates\gradle\wrapper

#### What I found
[http://stackoverflow.com/questions/42548186/cordova-run-android-issue-at-sdk-tools-version-25-3-1](http://stackoverflow.com/questions/42548186/cordova-run-android-issue-at-sdk-tools-version-25-3-1)

**Comment by stevengill** [comment]
We are aware of this bug. The latest android tools changed and we have to update cordova-android itself with the fix. 

Issue: https://issues.apache.org/jira/browse/CB-12524

**Comment by TomAshley303** [comment]
I got around this by downloading the standalone android tools and extracting the templates folder.

**Comment by filmaj** [comment]
This issue is due to Google changing the structure of the Android SDK in their SDK Tools v26 release. As such, cordova had to scramble to land patches. The latest cordova-android releases after and including 6.2.1 should be able to handle this without issue.

As a workaround, I would suggest you:
1. Ensure you are running the latest phonegap-cli, as there were some cordova/phonegap integration hiccups recently
2. Ensure you add at least cordova-android v6.2.1 to your phonegap project.

I.e.:

```
$ phonegap create test
$ cd test
$ phonegap platform add android@6.2.1
```

Closing this issue. If you are still having problems, feel free to re-open.
